### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by candlehope** [Antimarkovnikov/AHC_CYOA#1]
Just wanted to thank you for all the work you've done. I've printed 4 books and now plan on printing Dream Eaters. They came out great and are such a nice addition! I also noticed your tMG reference on your profile. A person of exquisite taste!

**Comment by Antimarkovnikov** [comment]
Thank you! I'm glad you're enjoying it! I personally wait to print mine out until the Return to Version comes out.
And remember to DO EVERY STUPID THING THAT MAKES YOU FEEL ALIVE!
