### ISSUE TITLE
Noted Issues - Alice in Wonderland

### ISSUE THREAD

**Issue by Drafghast** [Antimarkovnikov/AHC_CYOA#12]
- Sibling Rivalry - p156 (setup): The wrong icon is used for the Chessmen deck here.
- Sibling Rivalry - p161 (Hand over the rattle...): Should instead point to page 162.
- Sibling Rivalry - p161 (Alright, you win...): Should instead point to page 164.
- Sibling Rivalry - p166 (...from page 161...): Should instead be "...from page 157...".
- Interlude - The Lion and the Unicorn - p169/174 (The Investigators must decide...): Both options show "If we don't settle...". The second option in both cases should be "We're not about to risk our necks for these blundering idiots."
- (side note for above: I think it's unclear how the upper option leads to "All for One, One for All", despite that being how it is originally printed. Likely nothing to be done for it, just reporting our tables' experiences.)
- Lucid Nightmare (Alice's Assistance) - p219 (Check the Campaign Log): The paragraph beginning with "If the Hare couldn't cope..." should be part of the above one ("The Hare and Hatter..."). As written, this could cause decks containing cards for each instance.
- Lucid Nightmare (Alice's Assistance) - p219 (Check the Campaign Log): The paragraph beginning with "If one of the Tweedles..." should be part of the above one ("The Tweedles learned..."). As written, this could cause decks containing cards for each instance.
- Lucid Nightmare - p221 (When the game is complete): "If one investigator resigned" should instead read "If at least one investigator resigned".
- Lucid Nightmare - p221 (Otherwise,): Should instead point to page 228.
- Lucid Nightmare - p221 (If Resolution 2...): Should instead point to page 224.
- Lucid Nightmare - p221 (If Resolution 5...): Should instead point to page 230.
- Lucid Nightmare - p223 (We have to...): Should instead point to page 224.
- Lucid Nightmare - p223 (We can't...): Should instead point to page 226.

**Comment by Antimarkovnikov** [comment]
Oh! Thank you so very much! I'll get those updated post haste!

**Comment by Drafghast** [comment]
Thank you for all of your hard work! If this kind of thing is helpful to you, I'd be happy to help with more as I find them.

**Comment by Antimarkovnikov** [comment]
> XSibling Rivalry - p156 (setup): The wrong icon is used for the Chessmen deck here. **Also the wrong one for Sibling Rivalry**
> XSibling Rivalry - p161 (Hand over the rattle...): Should instead point to page 162.
> XSibling Rivalry - p161 (Alright, you win...): Should instead point to page 164.
> XSibling Rivalry - p166 (...from page 161...): Should instead be "...from page 157...".
> XInterlude - The Lion and the Unicorn - p169/174 (The Investigators must decide...): Both options show "If we don't settle...". The second option in both cases should be "We're not about to risk our necks for these blundering idiots."
> (side note for above: I think it's unclear how the upper option leads to "All for One, One for All", despite that being how it is originally printed. Likely nothing to be done for it, just reporting our tables' experiences.)
> XLucid Nightmare (Alice's Assistance) - p219 (Check the Campaign Log): The paragraph beginning with "If the Hare couldn't cope..." should be part of the above one ("The Hare and Hatter..."). As written, this could cause decks containing cards for each instance.
> XLucid Nightmare (Alice's Assistance) - p219 (Check the Campaign Log): The paragraph beginning with "If one of the Tweedles..." should be part of the above one ("The Tweedles learned..."). As written, this could cause decks containing cards for each instance.
> XLucid Nightmare - p221 (When the game is complete): "If one investigator resigned" should instead read "If at least one investigator resigned".
> XLucid Nightmare - p221 (Otherwise,): Should instead point to page 228.
> XLucid Nightmare - p221 (If Resolution 2...): Should instead point to page 224.
> XLucid Nightmare - p221 (If Resolution 5...): Should instead point to page 230.
> XLucid Nightmare - p223 (We have to...): Should instead point to page 224.
> XLucid Nightmare - p223 (We can't...): Should instead point to page 226.
> 

Okay. I've gone through and updated all the errors you found... *WHEW* There were a lot of them.  Thank you so much!  All of the numbering is done manually so that's where a lot of the problems come in.  But in this one there seems to be a few sections I just didn't finish updating once I added them in or didn't pay close enough attention to.

**Comment by Antimarkovnikov** [comment]
>If this kind of thing is helpful to you, I'd be happy to help with more as I find them.

I would LOVE for this kind of feedback.  Proofing these books is one of the harder parts for me to do.  And there are always things that slip by... As you can see from the EXTENSIVE Changelog.
