### ISSUE TITLE
Noted Issues - Challenge Scenarios - 2016-2021

### ISSUE THREAD

**Issue by Drafghast** [Antimarkovnikov/AHC_CYOA#13]
Death Itself:
Omission - pg31 - The last line should read "The investigators successfully completed the challenge! Congrats!"
Omission - pg33 - The last line should read "The investigators successfully completed the challenge! Congrats!"

Bad Blood:
Typo - pg58 - "Agnes can collect memories..." references the Bless icon, rather than the correct one, which should be the Free Action icon.

By The Book:
Typo - pg68 - In the first text block, "Dark Cult" should be italicized.

Red Tide Rising:
Typo - pg81 - "If no resolution was reached and at least one investigator resigned," should instead read "If no resolution was reached because each investigator resigned,".

**Comment by Antimarkovnikov** [comment]
Fixed!  Thanks again!
