### ISSUE TITLE
Noted Issues - Night of the Zealot / Return to the Dunwich Legacy (bookmark) / The Dunwich Legacy (Optional Variant)

### ISSUE THREAD

**Issue by Drafghast** [Antimarkovnikov/AHC_CYOA#14]
Overall, just some minor formatting stuff for this round. This proofreading pass includes Night of the Zealot, The Dunwich Legacy, and the Return to the Dunwich Legacy bookmark. I couldn't find anything gamebreaking or immersion-shattering. Also, good on you for including the updates from the official FAQ in Resolution 0 of Blood on the Altar. It threw me for a bit until I remembered that existed. 

Night of the Zealot - 
    The Devourer Below:
    Formatting - pg30 - The last sentence has the background tentacle image blocking out the word "the". 

Return to the Dunwich Legacy (bookmark):
    Typo - "Return to Extracurricular Activities" has the word Extracurricular misspelled.

The Dunwich Legacy (Optional Variant) - 
    Prologue:
    Change (recommendation, no error made) - pg9 - Given that this is the Optional file, which is referenced only in the Table of Contents, would it make sense to include a reference to the "No Time to Waste" custom page here? A small note about it could also/instead be included in Preface (pg7?). My thought process here is that as this is a CYOA-style book, many (especially those that don't know what to look for) won't turn to a page unless specifically told to, even on a second playthrough. 1.85 cents and all.

    Extracurricular Activity:
    Formatting - pg11 - Both iterations of "The Night is Still Young" and "The Hour is Late" should be italicized.

    Armitage's Fate:
    Typo - pg39 - Under Check the Campaign Log, "If this the investigators were unconscious for several hours." should instead read "If _the investigators were unconscious for several hours:_"
    Formatting - pg43 - "Armitage's Fate" should be italicized.
    
    Miskatonic Museum:
    Formatting - pg48 - Both iterations of "Restricted Hall" and "Olaus Wormius Translation" should be italicized.
    Formatting - pg55 - Both iterations of "Olaus Wormius Translation" should be italicized.

    The Essex County Express:
    Formatting - pg61 - All iterations of "Olaus Wormius Translation" should be italicized.
    Formatting - pg61 - "If an investigator with The Necronomicon..." should have the passage "the Necronomicon was stolen" italicized. 
    (very minor) Typo - pg61 - There is an extra period at the end of the sentence "The associated card...".

    Blood on the Altar:
    Formatting - pg73 - All iterations of "Olaus Wormius Translation" should be italicized.
    Formatting - pg75 - All iterations of "Olaus Wormius Translation" should be italicized.
    Formatting - pg79 - All iterations of "Olaus Wormius Translation" should be italicized.

    Lost in Time and Space:
    Numbering - pg123 - Both options under "Check the Campaign Log:" are incorrect. They should instead point to pages 154 for the calmed option, and 156 for the warned option.
    Numbering - pg125 - Both options under "Check the Campaign Log:" are incorrect. They should instead point to pages 154 for the calmed option, and 156 for the warned option.
    Numbering - pg127 - Both options under "Check the Campaign Log:" are incorrect. They should instead point to pages 154 for the calmed option, and 156 for the warned option.

    Standalone Mode:
    Formatting - pg133 - In Scenario II, the "K" in "Dr. Henry..." should not be capitalized.
    Typo - pg134 - In Scenario V, "Powder of Ibn-Ghazi" is incorrectly spelled as "...Ibin...".
    Typo - pg134 - In Scenario V, "Broods" should instead be "Brood" (while you are technically grammatically correct, so buyer's choice, I guess?).
    Typo - pg135 - In Scenario VI, "Broods" should instead be "Brood" (see above).
    
    No Time to Waste:
    Typo - pg143 - The first text block should instead start with "Check the Campaign Log. If _Naomi has the investigators’ back:_...". 
    Typo - pg143 - The second text block should instead start with "Check the Campaign Log. If _the investigators rescued Dr. Francis Morgan:_...".
    Typo - pg143 - The final text block before the page redirect should instead start with "Check the Campaign Log. If _the investigators were unconscious for several hours:_...".

**Comment by Antimarkovnikov** [comment]
You know.  Initially I was annoyed at myself for HOW MANY errors you found. But I take it as high praise that you took the time to find and correct all of these errors. AND THEN! AND THEN, I saw that you even formatted the errors so it'd be easy for me to put them into the Changelog.  You are INDEED the best of humans!

Thank you SO MUCH! I'm updating these now.

**Comment by Antimarkovnikov** [comment]
Done! Thanks again!
