### ISSUE TITLE
Noted Issues - Return to the Path to Carcosa (bookmark) / The Path to Carcosa

### ISSUE THREAD

**Issue by Drafghast** [Antimarkovnikov/AHC_CYOA#15]
[[Editorial Note - I don't mind at all. I love helping to be a part of things and projects I enjoy, and honestly, I really missed having things to review and do generally editorial stuff on. Appreciate your hard work, and I'll definitely work down the whole list of books I own in time :) ]]

Return to The Path to Carcosa (bookmark) -
    Typo - front - In "Return To...Echos...", Echos should be spelled with the additional e (Echoes). Both are right, but this is consistent with the spellings found elsewhere and looks neater all matched up.

The Path to Carcosa -
    Table of Contents:
        Typo - pg5 - "Interlude I..." misspelled the word "Sketpic's". It should instead be "Skeptic's".
        Typo - pg5 - "Scenario V - A Phantom Truth" should instead be "Scenario V - A Phantom of Truth". This error is made throughout, and I'll reference it where I see it. 

     Prologue:
        Formatting - pg12 - "...Continued from..." at the top of the page should likely be italicized to match overall formatting. Also, maybe make a note to ensure she reads this aloud? I've had a few instances of uncertainty if this was a Hidden thing, but the campaign guide stresses it be read aloud. 

    Scenario III - Echoes of the Past:
        Typo - pg43 - There should be no period at the end of the sentence ending with "...Interviewed.".
        Typo/Numbering - pg43 - Under "Otherwise" at the bottom, there is no guide text. Recommend the addition of "Go to page 46.".
        Formatting - pg45 - "Continue to..." should have the word "Setup" capitalized.
        Formatting - pg46 - Replace the section starting with "Check your campaign log..." with "Check Campaign Log. If Sebastien Moreau is **not** listed under "VIPs Slain", search _The Last King_ encounter set for Sebastien Moreau (_Savage Hysteria_) and set them aside, out of play. This set is indicated by the icon to the right."
        Formatting - pg53 - In the first line, "...you took the onyx clasp." should be italicized.

    Scenario IV - The Unspeakable Oath:
        Formatting - pg67 - "Continue to..." should have the word "Setup" capitalized.
        Formatting - pg68 - Replace the section starting with "Check your campaign log..." with "Check Campaign Log. If Constance Dumaine is **not** listed under "VIPs Slain", search _The Last King_ encounter set for Constance Dumaine (_A Little Too Sociable_) and set them aside, out of play. This set is indicated by the icon to the right."
        Formatting - pg69 - In "Otherwise, use Act 2...", "Otherwise" should not be italicized.
        Formatting/Suggestion? - pg71 - The section starting with "Before resolving any..." should instead read 
        "_Before resolving any other resolution, if at least 1 investigator was defeated_
            Go to Page 72."
        Typo - pg77 - "A Phantom Truth" should instead read "A Phantom of Truth".

    Interlude II - Lost Soul:
        Typo (accounting for errata) - pg83 - The below should replace the entire resolution/guide text section.
        "_If an investigator resigned with the asset version of Daniel Chesterfield under their control_
            Go to Page 84.
        _If the enemy version of Daniel Chesterfield was in play when the scenario ended_
            Go to Page 86.
        _If neither of the above are true_
            Go to Page 88."

        Numbering - pg84 - "...from page 82..." should instead point to page 83.      
        Numbering - pg86 - "...from page 802..." should instead point to page 83.         
        Numbering - pg88 - "...from page 802..." should instead point to page 83.      
        Typo - pg90 - The passage "You ignored..." should instead read "_From page 85 (You ignored the warning)_.
        Typo - pg91 - "A Phantom Truth" should instead read "A Phantom of Truth".
        Typo - pg92 - The guide text "You heeded..." should instead read "_From page 85 (You heeded the warning)_.
        Typo - pg93 - "A Phantom Truth" should instead read "A Phantom of Truth".

    Scenario V - The Phantom of Truth:
        Typo - pg94 - "A Phantom Truth" should instead read "A Phantom of Truth".
        Formatting - pg95 - "Continue to Dream 1... Don't Get Lost." should instead read "Continue to Dream 1. Don't get lost.". I feel like it's done this way because the "don't get lost" is more of a suggestion, rather than a label for the chosen path.
        [[Editorial Approval - pg96/100 - I like that you didn't add any guide text on how to get to these pages, as they're purely there to confuse and have no legit pathing to get to them. Bravo :) ]]
        Formatting - pg99 - "Continue to Dream 1... Don't Get Lost." should instead read "Continue to Dream 1. Don't get lost.". See above for reasoning.
        Typo? - pg127 - The bottom line should instead read "Continue to Setup on page 130.".
        Formatting - pg129 - "Continue to..." should have the word "Setup" capitalized.
        Formatting - pg131 - Replace the section starting with "Check your campaign log..." with "Check Campaign Log. If Jordan Perry is **not** listed under "VIPs Slain", search _The Last King_ encounter set for Jordan Perry (_An Imposing Presence_) and set them aside, out of play. This set is indicated by the icon to the right."
        Formatting - pg139 - The passage "you found Nigel Engram." should be italicized.

    Scenario VI - The Pallid Mask:
        Typo? - pg143 - The bottom line should instead read "Continue to Setup on page 148.".
        Typo? - pg145 - The bottom line should instead read "Continue to Setup on page 148.".
        Typo - pg146 - The guide text "...Ishimaru's information." should instead read "_From page 143 (Haruko's Information)_".
        Formatting - pg147 - The passage "you opened a secret passageway." doesn't need to be italicized, as it's not being noted in the Campaign Log.
        Typo? - pg147 - The bottom line should instead read "Continue to Setup on page 148.".
        Formatting - pg148 - Replace the section starting with "Check your campaign log..." with "Check Campaign Log. If Ishimaru Haruko is **not** listed under "VIPs Slain", search _The Last King_ encounter set for Ishimaru Haruko (_Just Skin and Bones_) and set them aside, out of play. This set is indicated by the icon to the right."
        Formatting - pg149 - The passage "you opened a secret passageway," doesn't need to be italicized.
        Formatting - pg151 - The "Each" in "Each investigator..." doesn't need to be capitalized.  

    Scenario VII - Black Stars Rise:
        Typo? - pg159 - The bottom line should instead read "Continue to Setup on page 162.".  
        Formatting - pg161 - "Continue to..." should have the word "Setup" capitalized.      
        Formatting - pg162 - Replace the section starting with "Check your campaign log..." with "Check Campaign Log. If Ashleigh Clarke is **not** listed under "VIPs Slain", search _The Last King_ encounter set for Ashleigh Clarke (_Songs Die Unheard_) and set them aside, out of play. This set is indicated by the icon to the right."        
        Formatting - pg167 - The "Each" in "Each investigator..." doesn't need to be capitalized.  

    Scenario VIII - Dim Carcosa:
        Formatting - pg174 - The title, "Dim Carcosa", should be all capital letters in order to match the style for the rest of the book.
        Formatting - pg176 - The title, "Dim Carcosa", should be all capital letters in order to match the style for the rest of the book.
        Formatting - pg179 - All instances of That One Name That Starts With "H" , as well as "Beast of Aldebaran" don't need to be italicized. His title (the section in parentheses) can be italicized. 
        Formatting - pg181 - The section starting with "If no resolution..." should instead read "_If no resolution was reached (each investigator was defeated): Check Campaign Log._"

    Standalone Mode:
        Numbering - pg195 - The section for Curtain Call should direct to pg14. Pg10 is the Prologue, which isn't really helpful for a non-campaign game?
        Typo - pg198 - The section starting "During setup..." probably doesn't need to be there. It will already be accounted for in the standard Setup rules, and the players will choose their difficulty at that point. 
        Typo - pg198 - The section starting "Do not take..." should instead read "Do not take any additional weaknesses as instructed in this Setup."

**Comment by Antimarkovnikov** [comment]
Thank you! Once again! Quick question.  Which of the campaigns have you played?  Are you up to date?  If you are when I start making the Feast of Hemlock or the next Stand-Alone I might loop you into it from the start.

**Comment by Drafghast** [comment]
I've played all except for Edge of the Earth the normal way, not using the CYOA books. I've used the CYOA books for a only a few thus far. Feel free to bring me in from whenever you feel most comfortable doing so - I expect to run Feast of Hemlock fairly soon after it releases.

Looking forward to it!
________________________________

**Comment by Antimarkovnikov** [comment]
Excellent! I'll let you know when I've started it.  And I'll put it in a shared folder you can see. :)

**Comment by Antimarkovnikov** [comment]
*WHEW* OKAY! I finally got around to doing these updates!  Thank you SO MUCH again for editing my mangled nonsense! Here's some responses to your comments.

    Typo - pg90 - The passage "You ignored..." should instead read "_From page 85 (You ignored the warning)_.
    Typo - pg146 - The guide text "...Ishimaru's information." should instead read "_From page 143 (Haruko's Information)_".

On sections where it's ambigious as to where you could be coming from I chose not to list the page number.

    Formatting - pg95 - "Continue to Dream 1... Don't Get Lost." should instead read "Continue to Dream 1. Don't get lost.". I feel like it's done this way because the "don't get lost" is more of a suggestion, rather than a label for the chosen path.

I removed the capitalization but kept the elipsies

    [[Editorial Approval - pg96/100 - I like that you didn't add any guide text on how to get to these pages, as they're purely there to confuse and have no legit pathing to get to them. Bravo :) ]]

I do love this as well.  They serve the same function as dream 5 in the original campaign guide.


    Formatting - pg151 - The "Each" in "Each investigator..." doesn't need to be capitalized. 

Randomly campitalizing words is one of the things that I mess up THE MOST.

    Typo - pg198 - The section starting "During setup..." probably doesn't need to be there. It will already be accounted for in the standard Setup rules, and the players will choose their difficulty at that point. 

Seems like both have been done.  There's an addition -3 already in the bag setup.  AND it says to add the standard Chaos Token.  I might just remove the extra minus 3 and indicate for the players to pick their difficulty

**Comment by Antimarkovnikov** [comment]
Closed
