### ISSUE TITLE
German "Translation"

### ISSUE THREAD

**Issue by DerKaese** [Antimarkovnikov/AHC_CYOA#16]
Hi guys,
loving the work you put into the books and want to print those for myself, but in german.
I started grabbing the stuff out of your pdfs and replacing it with the german text, but it is quite the hassle.
Are you interested in me creating german Versions like the spanish one?
I would need the editable source to replace everything, so I don't mess up the formation when exporting from PDF.

Greetings,
Kaese

**Comment by Antimarkovnikov** [comment]
Sure! I think the hardest part about it is that I use Microsoft Publisher.  So if you have access to that I'll defintely share the files with you.

Thanks!

**Comment by DerKaese** [comment]
Got Publisher included in M365, so I would just have to see how different it is from Word :)

**Comment by Antimarkovnikov** [comment]
Okay! Shoot me an email and I'll share a folder with the files for translation in it. rugglesp at gmail
