### ISSUE TITLE
Thank you and a suggestion/request

### ISSUE THREAD

**Issue by schaufel4** [Antimarkovnikov/AHC_CYOA#17]
First off, I want to thank you for all of your amazing work! I'm working on getting everything set up for a big print run at Lulu right now :D Looking forward to Scarlet Keys, the new stand-alones, and Midsummer as well.

I was wondering, since you have added a few fan scenarios to the shelf, if you might one day give the [Pokemon Eldritch Edition campaign](https://boardgamegeek.com/thread/2481166/pokemon-eldritch-edition-full-release) your CYOA treatment? I can hope!

Thanks again!

**Comment by Antimarkovnikov** [comment]
Of course! TSK is complete now.  I might one day do the Pokemon campaign... But I don't have a strong interesting in Pokemon and there's only so much time in the day.  I'll remember that there are people who are excited about.
