### ISSUE TITLE
Return to Circle Undone - Prologue

### ISSUE THREAD

**Issue by dlloyd09** [Antimarkovnikov/AHC_CYOA#19]
A minor typo, I think, on p.28. For the tarot reading outcome, I think the options should be (III-VI) and (VII-IX), rather than (III-XI) and (XII-IX).

Thank you for making these guides; we just got our first set of these made up and they look amazing. We can't wait to do the rest, and greatly appreciate the time and effort these must take!

**Comment by Antimarkovnikov** [comment]
Thank you for finding that! I'll get it fixed.  I'm in the middle of updating a bunch of errors I've found over the last few months.  I'll get that updated soon!
