### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by taraba** [Antimarkovnikov/AHC_CYOA#2]
The changelog has not been updated since December. Can we trust that for all books except EotE? Wanted to print 2 and 3

**Comment by taraba** [comment]
Oop. I guess this is off topic for this, but I didn't want to increase the issues so much in a few minutes.
It would help if the Dunwich one said if the OV version could use the same cover. If we need separate covers between printers...

**Comment by Antimarkovnikov** [comment]
HI! Thanks for the questions!

I haven't gotten a chance to update the books in a hot minute.  One person
found an outside case that's not terribly clear in The Forgotten Age that I
need to fix.  And there's a few more things in the Dream Eaters I need to
fix.

Also, the Optional Variant SHOULD use the same cover as the original
version.

I should be able to get the forgotten age fixes done sometime this
weekend.  So check the website again on monday or sometime this week and I
should have the updated version up there.

Thanks,
Antimarkovnikov

**Comment by Antimarkovnikov** [comment]
I uploaded the updated Forgotten Age book! And I made a note about the OV
version of Dunwich! Let me know what you think of them when you get them
printed and if you find any errors let me know!

Thanks,
Antimarkovnikov
