### ISSUE TITLE
04 The Forgotten Age - Return to.pdf TYPO

### ISSUE THREAD

**Issue by VoidLock92** [Antimarkovnikov/AHC_CYOA#20]
![image](https://github.com/Antimarkovnikov/AHC_CYOA/assets/21327041/df5125e7-6a71-4bd5-a8e5-31baff00f2c0)
As you can see in the attached image there is a typo. I believe it should not say the investigators twice as it does currently.

**Comment by Antimarkovnikov** [comment]
Yup! That's a typo! Great catch. I'll have to update that soon.

**Comment by VoidLock92** [comment]
Sounds great, thanks for all the hard work you have put into these books. They are amazing and I plan on getting them all printed! I will read them all over once and make sure they are good to go before getting them printed, I will report if I find any other issues.

**Comment by sdarkwell** [comment]
As of this moment, the official file still contains this error.

I'm uncertain how to submit a pull request or even if one is desired.

That said, here is a copy that I corrected for my own use. Hope it helps:
[04 The Forgotten Age - Return to.pdf](https://github.com/user-attachments/files/16734533/04.The.Forgotten.Age.-.Return.to.pdf)

Thank you and be well!
\- S.

**Comment by Antimarkovnikov** [comment]
Thanks Sdarkwell! I've gotten behind on updating these because of life and working on The Feast of Hemlock Vale's book. I should be able to get these updated soon. I appreciate you posting your updated version!
