### ISSUE TITLE
Wiki Grammer Error 

### ISSUE THREAD

**Issue by VoidLock92** [Antimarkovnikov/AHC_CYOA#21]
I found another grammer error, this time it's on the wiki page. I will attach a picture and a link for you.

https://github.com/Antimarkovnikov/AHC_CYOA/wiki/

![Screenshot_20240215_032626.jpg](https://github.com/Antimarkovnikov/AHC_CYOA/assets/21327041/dba92ef3-efb0-47ea-a8bb-97677391b0ea)

This should not say "makes"

"This forces the players to make that decision without the knowledge that they shouldn't have."

Not a huge deal, and it's not in a book so that's good 😁 just trying to help.

**Comment by Antimarkovnikov** [comment]
Fixed! Thank you!
