### ISSUE TITLE
Out of date text on some books.

### ISSUE THREAD

**Issue by VoidLock92** [Antimarkovnikov/AHC_CYOA#22]
I notice some of the text is out of date in reference to the old packaging method of mythos packs. I was wondering if it is possible for the PDFs to be altered to update the text in some areas on our own? Or do you update the books yourself? I just was reading through some areas before getting them printed and noticed for instance in The Dunwich Legacy...

"PREFACE
e Dunwich Legacy is a campaign for Arkham Horror: e
Card Game for 1–4 players. “Extracurricular Activity” and “7e
House Always Wins” can be found in e Dunwich Legacy deluxe
expansion. “7e Miskatonic Museum,” “7e Essex County Express,”
“Blood on the Altar,” “Undimensioned and Unseen,”
“Where Doom Awaits,” and “Lost in Time and Space” can be
found in the six Mythos Packs of the same titles within e Dunwich
Legacy cycle."

In the new updated texts and campaign guide it states...

"The Dunwich Legacy is a campaign for Arkham Horror: The Card
Game for 1–4 players. The Dunwich Legacy contains eight scenarios:
“Extracurricular Activity,” “The House Always Wins,” “The
Miskatonic Museum,” “The Essex County Express,” “Blood on the
Altar,” “Undimensioned and Unseen,” “Where Doom Awaits,” and
“Lost in Time and Space.” Each of these scenarios may also be played
on its own in Standalone Mode."

While this will have no impact on the function of the book, I was just curious before I had them printed.

**Comment by Antimarkovnikov** [comment]
I doubt I will update this as it doesn't have any impact.
