### ISSUE TITLE
Font issue in P1 Challenge Scenarios

### ISSUE THREAD

**Issue by ChristopherS** [Antimarkovnikov/AHC_CYOA#23]
![image](https://github.com/Antimarkovnikov/AHC_CYOA/assets/1385247/97280f90-57fa-4b49-8f04-d1edeee190b4)
It looks like the icons for the chaos tokens are using the wrong symbols.

**Comment by Antimarkovnikov** [comment]
WOW! Yeah. Bad error! I fixed it.  There was a problem with the font.  Thank you for finding this.  It took so long to update since I was working on Hemlock Vale.
