### ISSUE TITLE
Return to Circle Undone, resolution typos

### ISSUE THREAD

**Issue by dlloyd09** [Antimarkovnikov/AHC_CYOA#25]
On page 205 of the Return to the Circle Undone book, the resolution options direct players to either page 182 or page 184 based on the campaign state, but I believe those references should actually be to page 206 or page 208, respectively, as 182/184 send you back to scenario setup instructions. Thank you!

**Comment by sdarkwell** [comment]
As of this moment, the official file still contains this error.

I'm uncertain how to submit a pull request or even if one is desired.

That said, here is a copy that I corrected for my own use. Hope it helps:
[05 The Circle Undone - Return to.pdf](https://github.com/user-attachments/files/16734735/05.The.Circle.Undone.-.Return.to.pdf)

Thank you and be well!
\- S.

**Comment by Antimarkovnikov** [comment]
Thanks Sdarkwell! I've gotten behind on updating these because of life and working on The Feast of Hemlock Vale's book.  I should be able to get these updated soon.  I appreciate you posting your updated version!

**Comment by Antimarkovnikov** [comment]
Fixed!
