### ISSUE TITLE
P1 Challenge Scenarios.pdf - Text overlapping images has noticeable compression artifacts

### ISSUE THREAD

**Issue by sdarkwell** [Antimarkovnikov/AHC_CYOA#26]
**Hello,**

Text overlapping images displays noticeable compression artifacts, manifesting as jagged text and dithering surrounding it.

This occurs throughout the document, but two examples are provided below:

**Page 22**
![image](https://github.com/user-attachments/assets/4da61818-e2b9-4745-a825-58b2fee055d4)

**Page 27**
![image](https://github.com/user-attachments/assets/b23683a1-d3ad-41f4-b1f6-cdca523d1804)

**Page 39**
![image](https://github.com/user-attachments/assets/4af9b84a-039e-4fbc-b341-459583c2b7f6)

**Thank you and be well!**
\- S.

**Comment by Antimarkovnikov** [comment]
Fixed! Thank you for pointing it out.  That's a very easy error that slips by me often.  If you look at the other books I'm sure you'd find more errors like these.  Thanks again for finding them!
