### ISSUE TITLE
Noted Issues - Stand-Alones 2021-2024

### ISSUE THREAD

**Issue by Drafghast** [Antimarkovnikov/AHC_CYOA#28]
[[Editor's Comment - It took me a little while to get this one done. It was both fairly excessive, and it took me a while to start due to my copy of The Midwinter Gala getting delayed.]]

[[Editor's Note - this is labeled as "S2 Stand-Alones 2021-2024" in the Wiki form and the site at large, but is titled within the file as "S2 Stand-Alones 2020-2024". This may well be a non-issue, but bears noting.]]

Overall - it seems that in the context of scenarios, "stand-alone" should instead be written as "standalone". While those would strictly be typos, the fact that you've been consistent with it within your works, including titles, it's likely not worth the time and effort to fix at this point. If it ain't broke, don't fix it and all :) 

Preface - 
Typo - pg6 - _Machinations Through Time_ was released in 2022, not in 2021. _Fortune and Folly_ was released in 2023, not 2022. Not really a big deal, but easy enough to fix.

Stand-Alone VII - Barkham Horror:
Formatting - pg8 - In the first passage, "The Meddling of Meowlathotep" should be italicized. 
Typo - pg9 - The first section of "Stand-Alone Mode" has "...standalone scenario", but to be internally consistent, this should probably instead be "...stand-alone scenario".
BACON BACON BACON! - pg16 - "BACON!" [[No Notes :)]]
Formatting - pg17 - At the bottom of the page, in the choice "Nope, Food", "Food" shouldn't be capitalized. 
Typo - pg20 - The first line should be "its", not "it's".
FOOOOOOOOD - pg22 - FOOD (re. BACON!)

Stand-Alone VIII - War of the Outer Gods: [[lots of small errors in this one]]
Clarification - pg34 - I noticed that while the source material lists the colors and cults in the blue, green, red order, you have it listed as green, blue, red. This seems to correspond to the listed "faction order" for sequences. Neat! Also, props for color-coding the color words for the factions!
Typo - pg34 - In the last section, "...on the order announced by the vent organizer" should instead read "...in the order announced by the event organizer".
Typo - pg36 - In the section beginning "During the...", the word "attack" is missing an s at the end. 
Typo - pg36 - In the section beginning "During the...", the word "it's" should instead be "its".
Typo (?) - pg38 - It looks like you swapped the placement of the Swarming mechanic and the Wards mechanic. I'm guessing this was deliberate, and parallels the change in listed faction order? Not a big deal, just noting.
Formatting - pg38 - In the first non-title line of the Swarming X section, the word "Swarming" shouldn't be capitalized. 
Typo - pg39 - In the section below "Place around this location", only the word "around" in "around a location" should be in quotes.
Typo - pg40 - The first section of "Game Mode" has "standalone" a few times, but to be internally consistent, this should probably instead be "stand-alone".
Typo - pg40 - The title of Standalone Mode should probably instead be Stand-Alone Mode.
Formatting - pg42 - In the first section, "Epic Multiplayer Mode" should be italicized.
Typo - pg42 - At the bottom of the section beginning "Each of the three...", the word "vent" should instead be "event".
Typo - pg42 - In the last section, the word "vent" should instead be "event".
Typo - pg43 - The back half of the first sentence is missing a comma and one instance of "the", and should instead read "...during act 1 or act 2, add doom to the agenda...".
Typo - pg43 - In the listed example, the sentence beginning "Doom placed...", the section "...copy of an agenda..." should instead read "copy of any agenda...".
Typo - pg43 - In the listed example, the last sentence should instead read "_The event organizer is tasked with keeping track
of the doom that is placed on each agenda as the event progresses, and notifies the players when any particular agenda deck has accumulated enough doom to advance._"
Formatting - pg43 - In the Time Limit section, "Epic Multiplayer Mode" should be italicized.
Typo - pg43 - The sentence at the end starting with "When this time limit..." should instead read "When this time limit has passed, either all of the investigators are defeated, or the event organizer may decide to have any investigators that are still playing advance directly to the version of agenda 3b for the faction that is in the lead, after which those investigators have **30 minutes** to defeat the **_Ancient One_** that has been summoned."
Formatting - pg44 - In the Tips for the Event Organizer section, "Epic Multiplayer Mode" should be italicized.
Typo - pg44 - In the section starting "Track the global...", the second sentence should start with the word "Then", not "The".
Typo - pg44 - In the second sentence of the section starting "Periodically...", the phrase "...and inform then..." should instead be "...and inform them...".
Typo - pg44 - In the first line of the section starting "It can be useful...", the word "ot" should be "to". 
Typo - pg44 - There is a period missing after the phrase "...one-third for each agenda in the agenda deck".
Typo - pg44 - In the bottom section, the word "vent" should be "event".
Typo - pg44 - In the bottom section, the word "tack" should be "track".
Typo - pg45 - In the top section, the word "the" is missing from before the first "event".
Typo - pg46 - At the end of the paragraph starting "You have spent...", "conflicts'" should instead be "conflict's". [[I guess we're to assume that this is all a single conflict, rather than multiple?]]
Typo - pg47 - In the second section, the set name "Swarm of Assimilations" shouldn't have an "s" at the end of Assimilation.
Typo - pg47 - At the end of the second section, the phrase "...included int the..." should instead be "...included in the...".
Typo - pg47 - In the section starting "Set the Hub...", the word "beings" should be replaced by "begins".
Typo - pg47 - In the section starting "Set the 5...", the word "Porta" should be "Portal".
Typo - pg47 - In the section starting "Shuffle the...", the words "of the" can be removed. 
Typo - pg53 - In the first section, the word "tory" should instead be "story".
Typo - pg53 - In the last section, the word "ears" should instead be "earns". 
Typo - pg55 - In the first section, the word "tory" should instead be "story".
Formatting - pg56 - On the first line, "Shape" doesn't need to be capitalized. 
Typo - pg56 - On the first line, there is a missing comma after "formless".
Typo - pg56 - The first line of the last section should replace the word "overserve" with "observe".
Typo - pg56 - In the last section, the phrase "...hundreds of thousands..." should replace the word "of" with "or".
Typo - pg57 - In the first section, the word "tory" should instead be "story".
Typo - pg58 - In the first sentence, the word "graining" should instead be "groaning".
Typo - pg59 - In the first section, the word "tory" should instead be "story".

Stand-Alone IX - Machinations Through Time:
Typo - pg67 - In the Story Cards section, "card type" should be a single word "cardtype". [[Apparently?]]
Formatting - pg67 - In the Story Cards section, the word "Setup" should be bolded. 
Formatting - pg68 - The order that the rules terms are presented in should have Announce following Story Cards. Instead, it follows Patrol. Not sure if there's a reason for this one. 
Formatting - pg69 - In the last section, "Epic Multiplayer Mode" should not be italicized, in order to help it stand out from the surrounding passage. 
Typo - pg71 - The first section of "Game Mode" has "standalone" a few times, but to be internally consistent, this should probably instead be "stand-alone".
Typo - pg71 - The title of Standalone Mode should probably instead be Stand-Alone Mode.
Typo - pg71 - For Hard difficulty, there should be one fewer 0 token in the bag (0, 0, –1, –1, –1, –2, –3, –4, –6, etc).
Formatting - pg75 - "Arkham Advertiser" should be italicized. 
[[Editor's Note - pg 76 - Love the special formatting here, and the attention to detail in capturing the date and volume/number. Well done!]]
Formatting - pg82 - In the second section, "Single Group Mode" should be italicized. 
?Formatting? - pg82 - The section starting "Put the A Noble..." _should_ have different italicization than what you have, but honestly, I like yours more. I wouldn't change that here.

Stand-Alone X - Fortune and Folly:
Typo - pg105 - The first section of "Game Mode" has "standalone", but to be internally consistent, this should probably instead be "stand-alone".
Typo - pg105 - The title of Standalone Mode should probably instead be Stand-Alone Mode.
Typo - pg106 - In the section starting "Each part...", the word "of" should instead be "is". 
Formatting - pg106 - In the section starting "After completing...", you can delete the space in the middle of "this". 
Typo - pg106 - In the section starting "After completing...", the word "instructions" should instead be "instructs". 
Typo - pg107 - In the bottom section, the section "...or if any investigator..." should replace the word "any" with "an". 
Typo - pg108 - In the section starting "For the purpose...", the word "coutn" should instead be "count". 
Typo - pg108 - In the section starting "'Sequential ran'...", add a k to the end of "ran".
Typo - pg108 - At the end of the section starting "If a card...", add "ed" to the end of the italicized "discard".
Typo - pg109 - The second line in the The Wellspring of Fortune section is missing a d at the end of "introduce".
Typo - pg111 - The first possible choice at the bottom is missing "ing" at the end of the first "play". 
Typo - pg116 - In the first section, the comma following "...than anyone could guess." should instead be a period. 
Formatting - pg118 - For the sake of clarity and consistency, I recommend that the section starting "What follows is..." be italicized. 
Typo - pg118 - In the section starting "The more money...", the word "tor" should instead be "for".
Typo - pg119 - In the section starting "The Wellspring", the word "taster" should instead be "faster".
Typo - pg119 - At the very end of the last section here, the quotation mark can be deleted. 
Typo - pg120 - The set name "Fortune's Chose" is missing a "n" at the end. 
?Formatting? - pg120 - (Calm Night) should be different, but I like the way you have it here. No need to change it. 
Formatting - pg121 - In the bottom section, the word "Stable" should be bold and italicized.
Typo - pg121 - At the end of the bottom section, the quotation mark can be deleted. 
Clarification - pg135 - Probably not worth changing at this junction, but I'm unsure as to why the routing points to both pg136 and pg138, when the content of each is identical. 
Typo - pg136 - At the end of the section starting "If you're able...", the quotation mark can be deleted. 
Typo - pg136 - At the end of the section starting "The casino provides...", the ending comma should instead be a period. 
?Formatting? - pg137 - The order of presented steps here differs from the source material. It doesn't matter overmuch, but figured I could call it out. 
Typo - pg138 - At the end of the section starting "If you're able...", the quotation mark can be deleted. 
Typo - pg138 - At the end of the section starting "The casino provides...", the ending comma should instead be a period. 
Typo - pg139 - The set name "Fortune's Chose" is missing a "n" at the end. 
?Formatting? - pg140 - The order of presented steps here differs from the source material. It doesn't matter overmuch, but figured I could call it out. 
Typo - pg143 - The section referencing "...cleaned out the house...", has a number of errors. It should be rewritten as follows - 
"If _you cleaned out the house_, put the Cash Cart into play at High Roller's Table. Otherwise, set it aside, out of play.".
Formatting - pg145 - In the section starting "In your campaign Log...", "Campaign" should be capitalized.
Formatting - pg147 - In the first section starting "In your campaign Log...", "Campaign" should be capitalized.
Typo - pg147 - In the second section starting "In your Campaign Log...", the word "choses" should be instead be "Chosen". 
Formatting - pg149 - In the first section starting "In your campaign Log...", "Campaign" should be capitalized.
Typo - pg149 - In the second section starting "In your Campaign Log...", the word "choses" should be instead be "Chosen". 
Typo - pg151 - In the first section, "part I" should likely instead be written as "part one", for internal consistency. 
Typo - pg151 - In the second section, the word "ears" should instead be "earns". 
Typo - pg151 - In the third section, there should be a comma following "were completed".
Formatting - pg151 - In the final section, both instances of "Fortune and Folly" should have their italicization swapped (the first one should be italicized, and the second should not be). 

Stand-Alone XI - The Midwinter Gala:
Typo - pg153 - The first section of "Game Mode" has "standalone", but to be internally consistent, this should probably instead be "stand-alone".
Typo - pg153 - The title of Standalone Mode should probably instead be Stand-Alone Mode.
Typo - pg160 - In the second line, there is a non-English character at the end of "behalf". This should be replaced with a "f". 
Typo - pg164 - There is a second quotation mark following the end of "...business arrangement" that can be removed.
Typo - pg166 - There is a second quotation mark following the end of "......Lodge's collection" that can be removed.
Typo - pg168 - There is a second quotation mark following the end of "...this old port" that can be removed.
Formatting - pg171 - In the section starting "Put the Bloodless Man...", the word "lantern" should be capitalized. 
Formatting - pg171 - In the last section, the word "Monster" should be bold and italicized.
?Formatting? - pg171 - The word "Rival" shouldn't be bold or italic, but I think I prefer it this way. No change needed. 
Formatting - pg174 - In the bold section, the word "Allied" should be italicized. 
Typo - pg174 - In the bold section, I recommend removing the last bit "If you allied with...". The following bits lead with "If you allied with..." for each choice, and omitting it in the first place seems cleaner. 

Optional Variants - The Midwinter Gala - Best Guests:
Typo - pg198 - The first section "Standalone Mode", but to be internally consistent, this should probably instead be "Stand-Alone Mode"
Formatting - pg199 - To remain consistent, the word "Rival" in the bottom section should be bold and italicized.

**Comment by Antimarkovnikov** [comment]
Thank you! Adding the issue here is great at notifying me. And I'll use the Google drive to be able to respond to specific questions or corrections.  I just got back from BusterCon, so now I should have some more time to go through these recommendations.

**Comment by Antimarkovnikov** [comment]
HOLY CRAP! This took me a long time to complete again.  Thanks again for all the feedback!  I have comments on the google drive doc.  Thanks again!
