### ISSUE TITLE
Noted Issues - The Feast of Hemlock Vale

### ISSUE THREAD

**Issue by Drafghast** [Antimarkovnikov/AHC_CYOA#31]
Noted Issues - The Feast of Hemlock Vale

[[
Editor's Note - You really did a great job with the art placement and choices in this one. No real game breaking issues either. Especially considering the sheer bulk of this - nice!
I did include one reference to the FAQ (a minor, common-sensey change), but a few of the ones I didn't mention were because it shouldn't strictly be possible, given the CYOA format (things like "You cannot play this scenario unless it is Night X."
]]

[[
Editor's Note - I made it in time! Happy holidays :) 
]]

Preface -
Typo - pg6 - "The Silent Wasteland" should instead be "The Silent Heath". 
Type - pg7 - In the Expert difficulty campaign chaos bag setup, the -7 token should instead be a -6.
Formatting? - pg7 - The two Continue options at the bottom of the page are unformatted - basically just two lines of text. Should this also be written as a CYOA prompt, like everything else?

Additional Rules -
Typo - pg8 - The last line of the first paragraph should replace the word "of" with "for". 
Typo - pg8 - The third line of the second paragraph should replace the word [letter?] "o" with "or".
Formatting (low pri) - pg9 - To match source formatting, the passage "River is a dreamboat" should be italicized. 
Typo - pg10 - In the first bullet entry, the word "of" is missing between "number" and "checked". 
Typo - pg10 - In the second-to-last bullet entry, the period following "zero" should be omitted.
Typo - pg11 - In the first paragraph, the word "arrange" should instead be "arranged". 
Typo - pg11 - In the second bullet entry, the second "locations" doesn't need that "s". 
Typo - pg11 - In the third bullet entry, the word "much" should instead be "must".

Prelude - Day One - 
Suggestion? - pg26 - I almost feel like the Codex links should also list the name, like in the source. It should reduce misrouting, and shouldn't impact anything negatively.
Formatting - pg32 - In the last sentence of the first paragraph, to closer match source formatting, the word "someone" should be italicized.
Formatting - pg36 - In the last sentence of the first paragraph, to closer match source formatting, the passage "Tales from Nevermore" should be italicized.

Prelude - The First Evening - 
Formatting - pg46 - In the action for the first choice, the sentence is missing a word or two. I recommend something like "Flip the book over to read the bottom of the page.", but your mileage may vary.
Formatting - pg50 - In the action for the first choice, the sentence is missing a word or two. I recommend something like "Flip the book over to read the bottom of the page.", but your mileage may vary.
Formatting - pg46 - In the action for the first choice, the sentence is missing a word or two. I recommend something like "Flip the book over to read the bottom of the page.", but your mileage may vary.
Formatting? - pg51 - In the third line, the word "more" has a weird space in it. I suspect it's a factor of the justification and is just gonna exist, but I felt I should mention it. 
Formatting - pg51 - In the bottom bullet entry, the sentence is missing a word or two. Same as above!

Prelude - Dawn of the Second Day - 
Formatting - pg64 - At the end of the first paragraph, to closer match the source, the word "right" should be italicized. 

Prelude - Day Two - 
Typo - pg67 - In the last bullet entry, the Copy/Paste got a bit of a workout (the sentence appears twice). 
Suggestion? - pg68 - I almost feel like the Codex links should also list the name, like in the source. It should reduce misrouting, and shouldn't impact anything negatively.
Typo - pg74 - In the first sentence, the quotation mark before the sentence starts doesn't need to exist. 
Formatting - pg76 - In the first bullet entry, the sentence is missing a word or two. Same as above!
Typo - pg87 - In the second bullet entry, the word "first" should be replaced by "next". 
Typo - pg89 - In the second bullet entry, the word "first" should be replaced by "next". 

Prelude - The Second Evening - 
Formatting - pg64 - In the second to last paragraph, to closer match the source, the word "something" should be italicized. 

Prelude - Day Three - 
Typo - pg125 - The encounter set "The Third Day" should instead be "The Final Day".
Suggestion? - pg126 - I almost feel like the Codex links should also list the name, like in the source. It should reduce misrouting, and shouldn't impact anything negatively.
Typo - pg138 - At the end of the first paragraph, there should be a quotation mark following "...Portland."
Formatting - pg146 - In the second bullet entry of the first set, the passage "The plan is underway" should be italicized.
Typo - pg146 - In the last bullet entry of the first set, the word "first" should be replaced by "final". 
Formatting - pg148 - In the second bullet entry of the first set, the passage "The plan is underway" should be italicized.
Formatting - pg148 - In the second bullet entry of the first set, the passage "The plan is underway" should be italicized.

Prelude - Night Three - 
Typo - pg159 - The encounter set "The Third Day" should instead be "The Final Day".
Typo - pg159 - At the end of the bullet entry starting "Put each location...", there is an extra "the" following "...location map on...".
Suggestion? - pg162 - I almost feel like the Codex links should also list the name, like in the source. It should reduce misrouting, and shouldn't impact anything negatively.
Typo - pg170 - According to the FAQ - the first part of the passage starting "If Gideon..." should replace the word "story" with "tale". 
Formatting - pg174 - On the first section starting "Go to...", there should be a space between "page" and "175".
Formatting - pg174 - In the final paragraph, to closer match the source, the name "The Lost World" should be italicized.  

Scenario - Written in Rock - 
Formatting - pg198 - In the bolded bullet entry, the "Written in Rock" name should be italicized. 
Suggestion? - pg199 - Codex links listing name note again :)
Note - pg200 - I don't know why we suddenly have different colors for different Codex entries here - but I kinda like it. Was there a particular reason that wasn't used throughout the first 200 pages?

Scenario - Hemlock House - 
Formatting - pg224 - That leading "Oh" lost its leading quotation mark - it's down before "about", on the sixth line down :P
Formatting - pg224 - On line 8, the word "something" should be italicized. 
Formatting - pg224 - On the last line, there should be a hyphen between "foul" and "smelling". 
Formatting - pg228 - On line 13, the word "something" should be italicized. 
Formatting - pg230 - On line 10, the word "something" should be italicized. 
    [[Editor's Note - the source doesn't italicize this instance, but I believe that to be in error, based on the other examples.]]
Suggestion? - pg235 - Codex links listing name note again :)
Typo - pg236 - In the first bolded section, "Silvie" is incorrectly spelled. It should be "Sylvie".
Typo - pg242 - On the upside-down half, following the section dealing damage, there is an additional period. 
    [[Editor's Note - I tend to have some difficulties reviewing the flipped sections in these books when I lack a physical copy (this is one of those cases). So, I may very well miss stuff, but will call them out when I see them.]]
Typo - pg 244 - The title "Enemy Location" at the top should be hyphenated, since that's the default for its cardtype.
    [[Editor's Note - I'm honestly a little disappointed that they didn't come up with a clever cardtype for this, but I guess it's evocative enough? And also I'm not coming up with anything as an example, so I can't complain too much.]]
Typo - pg244 - In the bottom bullet entry, everything following the section in parentheses should be removed (and returned to the Edge of the Earth from whence they came!).

Scenario - The Silent Heath - 
Kudos - pg258 - Great work on correcting the order of the displayed icons to match the set names! I saw it in the source and broke for a second :P
Formatting - pg259 - In the bottom bullet entry, the phrase in parantheses should be italicized. 
Formatting - pg260 - In the first bullet entry, both instances of "Horrors in the Rock" should be italicized. 
Typo - pg260 - There is an additional period at the end of the first bullet entry. 
Suggestion? - pg261 - Codex links listing name note again :)
Formatting - pg269 - On line 9, the word "different" should not be italicized. 
Formatting - pg271 - On line 9, the word "different" should not be italicized. 

Scenario - The Lost Sister - 
Suggestion? - pg285 - Codex links listing name note again :)
Formatting - pg292 - At the end of the bullet entry starting "Update your Campaign Log", the passage "Gideon found his treasure" should be italicized. 
Typo - pg296 - In the second paragraph, there is a quotation mark missing from before "Come here...".
Formatting - pg297 - At the end of the bullet entry starting "Update your Campaign Log", the passage "Gideon found his treasure" should be italicized. 
Formatting - pg299 - At the end of the bullet entry starting "Update your Campaign Log", the passage "Gideon found his treasure" should be italicized. 

Scenario - The Thing in the Depths - 
Formatting - pg308 - In the first sentence, the passage "Journey to the Center of the Earth" should be italicized. 
Suggestion? - pg317 - Codex links listing name note again :)

Scenario - The Twisted Hollow - 
Suggestion? - pg345 - Codex links listing name note again :)

Scenario - The Longest Night - 
Suggestion? - pg373 - Codex links listing name note again :)
Formatting - pg391 -In the second-to-last bullet entry, the passage starting "Each investigator may..." should be bolded.

Scenario - Fate of the Vale - 
Typo - pg396 - In the bullet entry starting "Shuffle the 4...", the page referenced for the diagram is incorrect in this format. It should instead reference page 397. 
    [Editor's Note - Technically, it's right, in that it matches the source, but it's inaccurate?]]
Formatting - pg396 - In the bullet entry starting "After drawing...", the second instance of "The Abyss" should be bolded. 
Suggestion? - pg399 - Codex links listing name note again :)
Formatting - pg407 - In the bullet entry referencing the Cosmic Emissary, both titles in parentheses should be italicized. 
Formatting - pg409 - In the bullet entry referencing the Cosmic Emissary, the first title in parentheses should be italicized. 
Note - pg410 - At the end of the first paragraph, strictly speaking, the word "full" shouldn't be italicized. But, I like it. Don't change a thing :)
Formatting - pg411 - Hey you nailed the italicization on this one! No notes!
Suggestion? - pg414 - Codex links listing name note, for the last time I think.
Typo - pg428 - In the first paragraph, there's a word missing from the first sentence. We can fix this by adding the word "and" before "clamber".
    [[Editor's Note - This is another instance where it's also incorrect in the source, and your version is identical to that. But we can improve this fairly easily.]]

Achievements - 
Formatting - pg440 - All instances of "The Feast of Hemlock Vale" and other scenario names should be italicized on this page. 
Formatting - pg441 - All instances of "The Feast of Hemlock Vale" and other scenario names should be italicized on this page. 

Epilogue - 
Suggestion? - pg446 - Codex links listing name note - oh no there was one more of these!
Formatting - pg448 - On the upside-down half, on the last line, the word "utterly" should be italicized. 
Kudos - pg451 - OK, I know this is just existing card art, but his face is just priceless. Very much "the heck did I just read?!". I love it.

**Comment by Antimarkovnikov** [comment]
Spectacular! Thank you SO MUCH for these notes!  I'll be going through this on my vacation over the next two weeks!

**Comment by Antimarkovnikov** [comment]
Okay. To directly answer the common comment about naming the codex entries.  I don't think I have space to put their full names for all of them.  And I'm torn between having just the first name or keeping them nameless.  There are some instances like in The Lost Sister where I think there are some spoilers in the codex names.  However, I also think that one main way you figure out where people are going for your second playthrough it looking at those codex names and kinda cheating at knowing what is where.

I think an overall compromise might be to put the first names of residents next to their entries but not anything that's not someone you might know.

**Comment by Antimarkovnikov** [comment]
Welp. This is what happens when I have two weeks off.  I finished the edits!  Thanks for giving them to me!  I also did post comments in the google drive folder.
