### ISSUE TITLE
Web of Dreams ending - wrong page reference

### ISSUE THREAD

**Issue by thatDavidCarr** [Antimarkovnikov/AHC_CYOA#32]
Hi, we've been playing through the campaigns recently and been loving the CYOA guides. 

We noticed page reference errors for endings that 'Break the rules of Ulthar', the Web of Dreams guide instructs to open Dream Quest at page 194, but that should be 198.

**Comment by Antimarkovnikov** [comment]
Thank you!  I can't believe I made this miskate 16 times in a row!
