### ISSUE TITLE
Innsmouth - Devil Reef - Page reference error

### ISSUE THREAD

**Issue by Ocelate** [Antimarkovnikov/AHC_CYOA#7]
The pages referenced for devil reef (P101 play order and P59 chronological) when asked if the mission failed/was successful are for the opposite result.

Thanks for putting these books together.

**Comment by Antimarkovnikov** [comment]
Thank you! I got those fixed and uploaded.  Sorry it took so long to respond.  Let me know if you find other errors. :)
