### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by PeFox** [Antimarkovnikov/AHC_CYOA#8]
Hi,
I found your awesome work and I was completely hooked. However, my better half plays only in German, so I was thinking to do an translation. What are you using for creating the PDFs? LaTex by any chance? Anyhow, I am just here to offer to do a German translation and share it, if you are willing to share the sources. Maybe starting with Night of the Zealot an then see how it works out? :)
My contact E-Mail is: Pete.Fuchs@gmail.com

Best Regards,
Pete

**Comment by Antimarkovnikov** [comment]
Hey!
Sorry this is almost a year late!  I am using Micrsoft Publisher to create the files. I'll Email you the files so you can try to work with them!

Thanks,
Antimarkovnikov
