### ISSUE TITLE
Typo in Return to Circle Undone pg. 11

### ISSUE THREAD

**Issue by mtwebb** [Antimarkovnikov/AHC_CYOA#9]
“This reading is **deal** if you want to add a **tough** of randomness or replay value to a scenario, but desire a more balanced effect.”

deal -> ideal
tough -> touch

These choose your own adventure versions are a blast.

**Comment by Antimarkovnikov** [comment]
HA! Oh good grief!  Even my own words have turned against me!  I'll get those changed soon. :)  Thanks for finding that.
